Repository engineering-truestate/IQOLCRM-frontend, pull requests merged in 2025-06, with the labels that each got.

#14 Documentation acn schema
  docs/ACN/schema.md
  images/ACN/ER_diagram.png
Labels: documentation

#15 Added Schema for Property Types in Restack
  docs/restack/post-rera-schema-stock.md
  docs/restack/pre-launch-schema.md
  docs/restack/pre-rera-schema-stock.md
  docs/restack/primary-schema.md
Labels: documentation

#33 Setup algolia
  package-lock.json
  package.json
  src/pages/acn/Requirements/RequirementPropertiesSelection.tsx
  src/pages/acn/Requirements/Requirements.tsx
  src/services/acn/properties/algoliaPropertiesService.ts
  src/services/acn/requirements/algoliaAcnReqService.ts
Labels: new feature

#36 firebase data connect for pre launch property in restack
  src/components/design-elements/DateInputUnixTimestamps.tsx
  src/components/design-elements/StateBaseNumberField.tsx
  src/components/helper/getUnixDateTime.ts
  src/components/restack/AddPreLaunchProjectModal.tsx
  src/hooks/restack/usePreLaunch.ts
  src/pages/dummy_data/restack_prelaunch_dummy_data.ts
  src/pages/restack/PreLaunch/PreLaunch.tsx
  src/pages/restack/PreLaunch/PreLaunchDetails.tsx
  src/services/restack/preLaunchService.ts
  src/store/actionTypes/restack/preLaunchActionTypes.ts
  src/store/actions/restack/preLaunchActions.ts
  src/store/index.ts
  src/store/reducers/restack/preLaunchReducer.ts
  src/store/reducers/restack/types.ts
Labels: enhancement

#37 Setup/algolia for QC inventory
  src/pages/acn/QCDashboard/QCDashboardPage.tsx
  src/pages/acn/QCDashboard/QCPropertyDetails.tsx
  src/pages/dummy_data/acn_qc_dummy_data.ts
  src/services/acn/qc/algoliaQcInventoryService.ts
Labels: enhancement
